### ISSUE TITLE
Error with version 1.0.1

### ISSUE THREAD

**Issue by jmartsch** [riasvdv/statamic-markdown-highlight#2]
Even after you fixed the namespace issue, I get an error while installing via
`composer require riasvd/statamic-markdown-highlight:1.0.1`. But now a different one:
```
 Illuminate\Foundation\ComposerScripts::postAutoloadDump
> @php artisan package:discover --ansi

   Symfony\Component\Debug\Exception\FatalThrowableError  : Class 'Rias\MarkdownHighlight\MarkdownHighlight' not found

  at P:\htdocs\dotnetic-statamic\vendor\statamic\cms\src\Providers\AddonServiceProvider.php:86
    82|
    83|     protected function bootFieldtypes()
    84|     {
    85|         foreach ($this->fieldtypes as $class) {
  > 86|             $class::register();
    87|         }
    88|
    89|         return $this;
    90|     }

  Exception trace:

  1   Statamic\Providers\AddonServiceProvider::bootFieldtypes()
      P:\htdocs\dotnetic-statamic\vendor\statamic\cms\src\Providers\AddonServiceProvider.php:44

  2   Statamic\Providers\AddonServiceProvider::Statamic\Providers\{closure}()
      P:\htdocs\dotnetic-statamic\vendor\statamic\cms\src\Statamic.php:240
```

**Comment by riasvdv** [comment]
Forgot an import, should be fixed in 1.0.2!

**Comment by jmartsch** [comment]
I only just got to try out the change. Unfortunately I still get the same error :(
I use beta34 from statamic

**Comment by jmartsch** [comment]
Here is what I see when I try to open the control panel:
![image](https://user-images.githubusercontent.com/551551/86786027-be95b900-c063-11ea-8238-59a7bc4ec5c3.png)

But I installed your plugin with `composer require rias/statamic-markdown-highlight:1.0.2`

**Comment by jmartsch** [comment]
Today everything is working fine. Don't know what the problem was 🤔
